name: gfeeds
base: core24
adopt-info: gfeeds
grade: stable
confinement: strict
compression: lzo

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkitgtk-6.0:
    bind: $SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkitgtk-6.0

parts:
  python-deps:
    source: .
    plugin: python
    build-packages:
      - libxml2-dev
      - libxslt1-dev
      - libjpeg-turbo8-dev
    python-packages:
      - attrs==22.2.0
      - beautifulsoup4==4.12.0
      - certifi==2022.12.7
      - chardet==5.1.0
      - charset-normalizer==3.1.0
      - colorama==0.4.6
      - cssselect==1.2.0
      - exceptiongroup==1.1.1
      - humanize==4.6.0
      - idna==3.4
      - iniconfig==2.0.0
      - lxml[html_clean]==6.0.2
      - packaging==23.0
      - Pillow==9.4.0
      - pluggy==1.0.0
      - Pygments==2.14.0
      - pytest==7.2.2
      - python-dateutil==2.8.2
      - python-magic==0.4.27
      - pytz==2022.7.1
      - readability_lxml==0.8.1
      - requests==2.28.2
      - six==1.16.0
      - soupsieve==2.4
      - tomli==2.0.1
      - urllib3==1.26.15
      - pybind11==2.10.3
    prime:
      - -usr/bin/activate
      - -usr/bin/activate.csh
      - -usr/bin/activate.fish
      - -usr/bin/Activate.ps1
      - -usr/bin/python
      - -usr/bin/python3
      - -usr/bin/python3.10
      - -usr/bin/pip
      - -usr/bin/pip3
      - -usr/bin/pip3.10
      - -usr/bin/wheel
      - -usr/lib/python3.10/dist-packages/pip*
      - -usr/lib/python3.10/dist-packages/setuptools*
      - -pyvenv.cfg
      - -lib
      - -lib64
      - -include
      - -share
    organize:
      bin: usr/bin
      lib/python3.12/site-packages: usr/lib/python3/dist-packages

  syndom:
    after: [ python-deps ]
    source: https://gitlab.com/gabmus/syndication-domination.git
    source-commit: "75920321062d682437f3fb0319dad227d8b18f6c"
    source-depth: 1
# ext:updatesnap
#   version-format:
#     ignore: true
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -DTO_JSON_BINARY=false
      - -DPYTHON_BINDINGS=true
      - -DHTML_SUPPORT=true
    build-environment:
      - PYTHONPATH: $CRAFT_STAGE/usr/lib/python3/dist-packages:$PYTHONPATH
      - CPPFLAGS: -I/usr/include/tidy
    build-packages:
      - libpugixml-dev
      - libtidy-dev
      - libfmt-dev

  blueprint-compiler:
    source: https://gitlab.gnome.org/jwestman/blueprint-compiler.git
    source-tag: "v0.6.0"
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    override-prime: ""

  gfeeds:
    after: [ syndom, blueprint-compiler ]
    plugin: meson
    source: https://gitlab.gnome.org/World/gfeeds.git
    source-tag: '2.2.0'
    source-depth: 1
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
      - PKG_CONFIG_PATH: /snap/webkitgtk-6-gnome-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:$PKG_CONFIG_PATH
      - PATH: /snap/webkitgtk-6-gnome-2404-sdk/current/usr/bin:$PATH
      - XDG_DATA_DIRS: /snap/webkitgtk-6-gnome-2404-sdk/current/usr/share:$XDG_DATA_DIRS
      - LD_LIBRARY_PATH: /snap/webkitgtk-6-gnome-2404-sdk/current/usr/lib:/snap/webkitgtk-6-gnome-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/webkitgtk-6-gnome-2404-sdk/current/usr/lib/webkitgtk-6.0:/snap/webkitgtk-6-gnome-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0:$LD_LIBRARY_PATH
      - PYTHONPATH: $CRAFT_STAGE/usr/lib/python3/dist-packages:${PYTHONPATH}
      - GI_TYPELIB_PATH: /snap/webkitgtk-6-gnome-2404-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/girepository-1.0:$GI_TYPELIB_PATH
    override-build: |
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i "${CRAFT_PART_INSTALL}/snap/gfeeds/current/usr/bin/gfeeds"
    build-snaps:
      - webkitgtk-6-gnome-2404-sdk/latest/stable
    meson-parameters:
      - --prefix=/snap/gfeeds/current/usr
      - --buildtype=release
    organize:
      snap/gfeeds/current: .
      usr/local: usr
    prime:
      - -snap/gfeeds
    parse-info: [usr/share/metainfo/org.gabmus.gfeeds.appdata.xml]

  deps:
    after: [ gfeeds ]
    plugin: nil
    stage-packages:
      - libtidy5deb1
      - libpugixml1v5
      - libfmt9
      - libmagic1t64
    prime:
      - usr/lib/*/libtidy.so.5deb1*
      - usr/lib/*/libpugixml.so*
      - usr/lib/*/libfmt.so*
      - usr/lib/*/libmagic.so*
      - usr/lib/file/magic.mgc
      - usr/share/*/magic*

plugs:
  webkitgtk-6-gnome-2404:
    interface: content
    target: $SNAP/webkitgtk-platform
    default-provider: webkitgtk-6-gnome-2404
slots:
  gfeeds:
    interface: dbus
    bus: session
    name: org.gabmus.gfeeds

apps:
  gfeeds:
    command: usr/bin/gfeeds
    extensions: [gnome]
    common-id: org.gabmus.gfeeds
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      LD_LIBRARY_PATH: $SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkitgtk-6.0:$LD_LIBRARY_PATH
      GI_TYPELIB_PATH: $SNAP/webkitgtk-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0:$GI_TYPELIB_PATH
      GDK_DEBUG: portals
      MAGIC: $SNAP/usr/share/misc/magic
    plugs:
      - network
      - network-status
      - unity7
      - system-observe
