name: gfeeds # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: gfeeds
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  syndom:
    source: https://gitlab.com/gabmus/syndication-domination.git
    source-commit: "75920321062d682437f3fb0319dad227d8b18f6c"
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -DTO_JSON_BINARY=false
      - -DPYTHON_BINDINGS=true
      - -DHTML_SUPPORT=true
    override-pull: |
      craftctl default
      pip install --prefix=$CRAFT_PART_INSTALL/usr pybind11==2.10.3
    build-packages:
      - libpugixml-dev
      - pybind11-dev
      - libtidy-dev
      - libfmt-dev
  gfeeds:
    after: [syndom]
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.gnome.org/World/gfeeds.git
    source-tag: '2.2.0'
    source-depth: '1'
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
      - PKG_CONFIG_PATH: /snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:$PKG_CONFIG_PATH
      - PATH: /snap/webkitgtk-6-gnome-2204-sdk/current/usr/bin:$PATH
      - XDG_DATA_DIRS: /snap/webkitgtk-6-gnome-2204-sdk/current/usr/share:$XDG_DATA_DIRS
      - LD_LIBRARY_PATH: /snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib:/snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib/webkitgtk-6.0:/snap/webkitgtk-6-gnome-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:$LD_LIBRARY_PATH
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/gfeeds.patch
    override-build: |
      craftctl default
      pip install --prefix=$CRAFT_PART_INSTALL/usr attrs beautifulsoup4 certifi chardet charset-normalizer colorama cssselect exceptiongroup humanize idna iniconfig lxml packaging pillow pluggy pygments pytest python-dateutil python-magic pytz readability-lxml requests six soupsieve tomli urllib3 Pygments 
      sed -e '1c#!/usr/bin/python3' -i $CRAFT_PART_INSTALL/usr/local/bin/*
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/gfeeds/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    build-packages:
      - blueprint-compiler
    build-snaps:
      - webkitgtk-6-gnome-2204-sdk/latest/stable
    meson-parameters:
      - --prefix=/snap/gfeeds/current/usr
      - --buildtype=release
    organize:
      snap/gfeeds/current: .
      usr/local: usr
    prime:
      - -snap/gfeeds
    parse-info: [usr/share/metainfo/org.gabmus.gfeeds.appdata.xml]

plugs:
  webkitgtk-6-gnome-2204:
    interface: content
    target: $SNAP/webkitgtk-platform
    default-provider: webkitgtk-6-gnome-2204
slots:
  gfeeds:
    interface: dbus
    bus: session
    name: org.gabmus.gfeeds
    
apps:
  gfeeds:
    command: usr/bin/gfeeds
    extensions: [gnome]
    common-id: org.gabmus.gfeeds
    environment:
      LD_LIBRARY_PATH: $SNAP/webkitgtk-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/webkitgtk-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkitgtk-6.0:$LD_LIBRARY_PATH
    
